### ISSUE TITLE
High Memory usage after running AlDente continuously for a month

### ISSUE THREAD

**Issue by A-Kun** [AppHouseKitchen/AlDente-Charge-Limiter#1394]
**MacBook (please complete the following information):**
 - MacBook Model (https://support.apple.com/en-us/HT201608): MacBook Air 13-inch, M3, 2024
 - macOS Version (https://support.apple.com/en-us/HT201260): 14.7.1 (23H222)
 - Charger Model (Apple, Third Party, Wattage,...): Apple 67W
 - Charging Cable (MagSafe 2, MagSafe 3, USB-C, Apple, Third Party,...): MagSafe 3
 - AlDente Pro or AlDente Free: AlDente Free
 - AlDente Version: 1.29
 - List or add screenshots of all enabled/disabled settings in AlDente: <img width="446" alt="pngout" src="https://github.com/user-attachments/assets/5b3b0aad-c6c1-4643-9746-4dd4eb8ad9bc" />
 - Please share a debug file the next time this happens so that we can assess this issue better. You can find a guide on How to generate and share a debug file on our blog(https://apphousekitchen.com/how-to-generate-and-share-a-debug-file/).
[aldentepro-debug-2024-12-14-18:15:42.txt](https://github.com/user-attachments/files/18138084/aldentepro-debug-2024-12-14-18.15.42.txt)
 - External Monitor connected? No
 - MacBook used in Clamshell Mode (with the lid closed)? No

**Describe the bug**
AlDente is using 1.16 GB of memory after leaving it running for a month. 

**To Reproduce**
1. Open AlDente
2. Run it for a month

**Expected Behavior**
AlDente should use a reasonable amount of memory even after running for a long time. 

**Screenshots and Screen Recordings**
If applicable, add screenshots or screen recordings of the issue to help explain your problem.
<img width="1072" alt="pngout" src="https://github.com/user-attachments/assets/a097f915-8d46-41fc-9a70-3a000b1f29f5" />

**Additional context**

**Comment by e-kotov** [comment]
Same here.

**Comment by MatthiasKerbl** [comment]
Hi everyone,

Thank you for making us aware of this. We will look into it and try to improve it.
Since a GitHub issue is already open for this (#1256), I will close this issue.

Best,
Matthias

**Comment by e-kotov** [comment]
> Since a GitHub issue is already open for this (#1256), I will close this issue.

But it's not the same. Over there the issue is about disk writes, here it's about memory usage. (though these may be connected... @MatthiasKerbl will of course know better)

**Comment by MatthiasKerbl** [comment]
> > Since a GitHub issue is already open for this (#1256), I will close this issue.
> 
> But it's not the same. Over there the issue is about disk writes, here it's about memory usage. (though these may be connected... @MatthiasKerbl will of course know better)

Hi @e-kotov,

You are right, my mistake.
So far, we have not been able to reproduce this issue. Do you know how to trigger it?

Best,
Matthias

**Comment by e-kotov** [comment]
> So far, we have not been able to reproduce this issue. Do you know how to trigger it?

Not yet. I currently have 25 days of uptime of macOS, but I have restarted Al Dente on the day when I posted the comment here. Since then (it's been one week), Al Dente is at 186 Mb uncompressed memory. Which is not a small footprint, but not too high for me to be concerned.

If I notice high usage again, I will report. Do you have any idea of what you would need from me or anyone else who spots this in terms of technical details...? A memory dump/sample using the Activity Monitor..?

**Comment by A-Kun** [comment]
I was able to reproduce this again after 24 days of uptime:
![pngout](https://github.com/user-attachments/assets/07be6be8-98a3-4420-916d-3ebb4648f39e)

**Comment by kbot983** [comment]
I have the same issue after 52 days of uptime

![Image](https://github.com/user-attachments/assets/2e7af06b-50e7-4be5-b5fa-13b3c2ac4d2d)

**Comment by leeronr** [comment]
I've noticed this happen several times, though I haven't noticed if its incremental.

Uptime 23+ days. 1.07GB in memory. 

M2 Pro MacBook Pro, 16GB, macOS 15.5

**Comment by Anywhere-Music-Player** [comment]
Same here 

<img width="836" height="906" alt="Image" src="https://github.com/user-attachments/assets/ca1ae2d3-f9a4-4083-b5c6-8c3ba84c821d" />
<img width="2200" height="1184" alt="Image" src="https://github.com/user-attachments/assets/a973427a-3861-4c62-9279-5ab6c5c8ccf6" />
<img width="1334" height="438" alt="Image" src="https://github.com/user-attachments/assets/5e31ac95-434c-4491-af0d-4366437639e2" />

**Comment by liguiyuang** [comment]
我这里也是有同样的问题，内存每天都在增加

**Comment by MatthiasKerbl** [comment]
Hi everyone,

We have just released AlDente 1.35, which includes a fix for this issue. To update to AlDente 1.35, open the app and navigate to Settings > Check for Updates.
Please report back if it works for you.

Best,
Matthias

**Comment by zh-impact** [comment]
Still have an issue when click the Schedule tab. I have posted the img on this issue -> https://github.com/AppHouseKitchen/AlDente-Battery_Care_and_Monitoring/issues/1611#issuecomment-3417695070
